# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilemapscalelevelswidget.ui'
#
# Created: Mon Mar  3 18:35:28 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TileMapScaleLevelsDockWidget(object):
    def setupUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setObjectName(_fromUtf8("TileMapScaleLevelsDockWidget"))
        TileMapScaleLevelsDockWidget.resize(286, 305)
        TileMapScaleLevelsDockWidget.setMinimumSize(QtCore.QSize(286, 305))
        TileMapScaleLevelsDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxIsActive = QtGui.QCheckBox(self.tab)
        self.checkBoxIsActive.setChecked(True)
        self.checkBoxIsActive.setTristate(False)
        self.checkBoxIsActive.setObjectName(_fromUtf8("checkBoxIsActive"))
        self.horizontalLayout.addWidget(self.checkBoxIsActive)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonInfo = QtGui.QToolButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInfo.setIcon(icon)
        self.buttonInfo.setIconSize(QtCore.QSize(22, 22))
        self.buttonInfo.setObjectName(_fromUtf8("buttonInfo"))
        self.horizontalLayout.addWidget(self.buttonInfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sliderZoomlevels = QtGui.QSlider(self.groupBox)
        self.sliderZoomlevels.setToolTip(_fromUtf8(""))
        self.sliderZoomlevels.setStatusTip(_fromUtf8(""))
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setSliderPosition(0)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoomlevels.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(0)
        self.sliderZoomlevels.setObjectName(_fromUtf8("sliderZoomlevels"))
        self.verticalLayout.addWidget(self.sliderZoomlevels)
        self.spinBoxZoomlevels = QtGui.QSpinBox(self.groupBox)
        self.spinBoxZoomlevels.setKeyboardTracking(False)
        self.spinBoxZoomlevels.setMaximum(25)
        self.spinBoxZoomlevels.setObjectName(_fromUtf8("spinBoxZoomlevels"))
        self.verticalLayout.addWidget(self.spinBoxZoomlevels)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBoxDatasets = QtGui.QGroupBox(self.tab)
        self.groupBoxDatasets.setObjectName(_fromUtf8("groupBoxDatasets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxDatasets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonLoadOSM = QtGui.QToolButton(self.groupBoxDatasets)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/osm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadOSM.setIcon(icon1)
        self.buttonLoadOSM.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadOSM.setObjectName(_fromUtf8("buttonLoadOSM"))
        self.horizontalLayout_2.addWidget(self.buttonLoadOSM)
        self.comboBoxUserDatasets = QtGui.QComboBox(self.groupBoxDatasets)
        self.comboBoxUserDatasets.setObjectName(_fromUtf8("comboBoxUserDatasets"))
        self.horizontalLayout_2.addWidget(self.comboBoxUserDatasets)
        self.buttonLoadRefreshUserDatasets = QtGui.QToolButton(self.groupBoxDatasets)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadRefreshUserDatasets.setIcon(icon2)
        self.buttonLoadRefreshUserDatasets.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadRefreshUserDatasets.setObjectName(_fromUtf8("buttonLoadRefreshUserDatasets"))
        self.horizontalLayout_2.addWidget(self.buttonLoadRefreshUserDatasets)
        self.buttonLoadUserDataset = QtGui.QToolButton(self.groupBoxDatasets)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadUserDataset.setIcon(icon3)
        self.buttonLoadUserDataset.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadUserDataset.setObjectName(_fromUtf8("buttonLoadUserDataset"))
        self.horizontalLayout_2.addWidget(self.buttonLoadUserDataset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBoxDatasets)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.OptionsTab = QtGui.QWidget()
        self.OptionsTab.setObjectName(_fromUtf8("OptionsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.OptionsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBoxUseMercator = QtGui.QCheckBox(self.OptionsTab)
        self.checkBoxUseMercator.setChecked(False)
        self.checkBoxUseMercator.setTristate(False)
        self.checkBoxUseMercator.setObjectName(_fromUtf8("checkBoxUseMercator"))
        self.verticalLayout_5.addWidget(self.checkBoxUseMercator)
        self.checkBoxUseOnTheFlyTransformation = QtGui.QCheckBox(self.OptionsTab)
        self.checkBoxUseOnTheFlyTransformation.setChecked(False)
        self.checkBoxUseOnTheFlyTransformation.setTristate(False)
        self.checkBoxUseOnTheFlyTransformation.setObjectName(_fromUtf8("checkBoxUseOnTheFlyTransformation"))
        self.verticalLayout_5.addWidget(self.checkBoxUseOnTheFlyTransformation)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maxZoomlevelSpinBox = QtGui.QSpinBox(self.OptionsTab)
        self.maxZoomlevelSpinBox.setKeyboardTracking(False)
        self.maxZoomlevelSpinBox.setMinimum(-10)
        self.maxZoomlevelSpinBox.setMaximum(30)
        self.maxZoomlevelSpinBox.setProperty("value", 18)
        self.maxZoomlevelSpinBox.setObjectName(_fromUtf8("maxZoomlevelSpinBox"))
        self.gridLayout.addWidget(self.maxZoomlevelSpinBox, 1, 1, 1, 1)
        self.dpiSpinBox = QtGui.QSpinBox(self.OptionsTab)
        self.dpiSpinBox.setEnabled(False)
        self.dpiSpinBox.setKeyboardTracking(False)
        self.dpiSpinBox.setMinimum(72)
        self.dpiSpinBox.setMaximum(768)
        self.dpiSpinBox.setSingleStep(2)
        self.dpiSpinBox.setProperty("value", 96)
        self.dpiSpinBox.setObjectName(_fromUtf8("dpiSpinBox"))
        self.gridLayout.addWidget(self.dpiSpinBox, 2, 1, 1, 1)
        self.maxZoomlevelLabel = QtGui.QLabel(self.OptionsTab)
        self.maxZoomlevelLabel.setObjectName(_fromUtf8("maxZoomlevelLabel"))
        self.gridLayout.addWidget(self.maxZoomlevelLabel, 1, 0, 1, 1)
        self.minZoomlevelLabel = QtGui.QLabel(self.OptionsTab)
        self.minZoomlevelLabel.setObjectName(_fromUtf8("minZoomlevelLabel"))
        self.gridLayout.addWidget(self.minZoomlevelLabel, 0, 0, 1, 1)
        self.dpiLabel = QtGui.QLabel(self.OptionsTab)
        self.dpiLabel.setObjectName(_fromUtf8("dpiLabel"))
        self.gridLayout.addWidget(self.dpiLabel, 2, 0, 1, 1)
        self.minZoomlevelSpinBox = QtGui.QSpinBox(self.OptionsTab)
        self.minZoomlevelSpinBox.setKeyboardTracking(False)
        self.minZoomlevelSpinBox.setMinimum(-10)
        self.minZoomlevelSpinBox.setMaximum(30)
        self.minZoomlevelSpinBox.setObjectName(_fromUtf8("minZoomlevelSpinBox"))
        self.gridLayout.addWidget(self.minZoomlevelSpinBox, 0, 1, 1, 1)
        self.toggleDpiToolButton = QtGui.QToolButton(self.OptionsTab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/draw-freehand.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleDpiToolButton.setIcon(icon4)
        self.toggleDpiToolButton.setCheckable(True)
        self.toggleDpiToolButton.setObjectName(_fromUtf8("toggleDpiToolButton"))
        self.gridLayout.addWidget(self.toggleDpiToolButton, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.OptionsTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget)
        TileMapScaleLevelsDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TileMapScaleLevelsDockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.toggleDpiToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dpiSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TileMapScaleLevelsDockWidget)

    def retranslateUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setWindowTitle(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Tile Map Scale Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIsActive.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setToolTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Show information", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setStatusTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Show information", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Zoomlevel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDatasets.setTitle(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setToolTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "load OSM Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setStatusTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "load OSM Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setToolTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "refresh list of datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setStatusTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "refresh list of datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setToolTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "load selected dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setStatusTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "load selected dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseMercator.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Use World Mercator System", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseOnTheFlyTransformation.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Use \'On-The-Fly\' Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.maxZoomlevelLabel.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "max Zoomlevel", None, QtGui.QApplication.UnicodeUTF8))
        self.minZoomlevelLabel.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "min Zoomlevel", None, QtGui.QApplication.UnicodeUTF8))
        self.dpiLabel.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleDpiToolButton.setToolTip(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Allow to set dpi directly", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleDpiToolButton.setText(QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptionsTab), QtGui.QApplication.translate("TileMapScaleLevelsDockWidget", "Options", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
