# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilemapscalelevelswidget.ui'
#
# Created: Tue Feb 23 10:18:47 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TileMapScaleLevelsDockWidget(object):
    def setupUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setObjectName(_fromUtf8("TileMapScaleLevelsDockWidget"))
        TileMapScaleLevelsDockWidget.resize(474, 258)
        TileMapScaleLevelsDockWidget.setMinimumSize(QtCore.QSize(159, 161))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 430, 170))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolButtonIsActive = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/toolButtonIsActive.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonIsActive.setIcon(icon)
        self.toolButtonIsActive.setIconSize(QtCore.QSize(22, 22))
        self.toolButtonIsActive.setCheckable(True)
        self.toolButtonIsActive.setObjectName(_fromUtf8("toolButtonIsActive"))
        self.horizontalLayout_2.addWidget(self.toolButtonIsActive)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.toolButtonLayers = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/legend.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonLayers.setIcon(icon1)
        self.toolButtonLayers.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonLayers.setCheckable(False)
        self.toolButtonLayers.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButtonLayers.setObjectName(_fromUtf8("toolButtonLayers"))
        self.horizontalLayout_2.addWidget(self.toolButtonLayers)
        self.buttonLoadUserDataset = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadUserDataset.setIcon(icon2)
        self.buttonLoadUserDataset.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadUserDataset.setObjectName(_fromUtf8("buttonLoadUserDataset"))
        self.horizontalLayout_2.addWidget(self.buttonLoadUserDataset)
        self.buttonLoadRefreshUserDatasets = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/refresh.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadRefreshUserDatasets.setIcon(icon3)
        self.buttonLoadRefreshUserDatasets.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadRefreshUserDatasets.setObjectName(_fromUtf8("buttonLoadRefreshUserDatasets"))
        self.horizontalLayout_2.addWidget(self.buttonLoadRefreshUserDatasets)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonInfo = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help-hint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInfo.setIcon(icon4)
        self.buttonInfo.setIconSize(QtCore.QSize(22, 22))
        self.buttonInfo.setObjectName(_fromUtf8("buttonInfo"))
        self.horizontalLayout_2.addWidget(self.buttonInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.groupBoxZoomlevels = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxZoomlevels.setObjectName(_fromUtf8("groupBoxZoomlevels"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxZoomlevels)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sliderZoomlevels = QtGui.QSlider(self.groupBoxZoomlevels)
        self.sliderZoomlevels.setToolTip(_fromUtf8(""))
        self.sliderZoomlevels.setStatusTip(_fromUtf8(""))
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setSliderPosition(0)
        self.sliderZoomlevels.setTracking(False)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoomlevels.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(1)
        self.sliderZoomlevels.setObjectName(_fromUtf8("sliderZoomlevels"))
        self.verticalLayout.addWidget(self.sliderZoomlevels)
        self.spinBoxZoomlevels = QtGui.QSpinBox(self.groupBoxZoomlevels)
        self.spinBoxZoomlevels.setKeyboardTracking(False)
        self.spinBoxZoomlevels.setMaximum(25)
        self.spinBoxZoomlevels.setObjectName(_fromUtf8("spinBoxZoomlevels"))
        self.verticalLayout.addWidget(self.spinBoxZoomlevels)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_7.addWidget(self.groupBoxZoomlevels)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.OptionsTab = QtGui.QWidget()
        self.OptionsTab.setObjectName(_fromUtf8("OptionsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.OptionsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.OptionsTab)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 237, 201))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxHUD = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxHUD.setChecked(False)
        self.checkBoxHUD.setTristate(False)
        self.checkBoxHUD.setObjectName(_fromUtf8("checkBoxHUD"))
        self.verticalLayout_3.addWidget(self.checkBoxHUD)
        self.checkBoxUseMercator = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxUseMercator.setChecked(False)
        self.checkBoxUseMercator.setTristate(False)
        self.checkBoxUseMercator.setObjectName(_fromUtf8("checkBoxUseMercator"))
        self.verticalLayout_3.addWidget(self.checkBoxUseMercator)
        self.checkBoxUseOnTheFlyTransformation = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxUseOnTheFlyTransformation.setChecked(False)
        self.checkBoxUseOnTheFlyTransformation.setTristate(False)
        self.checkBoxUseOnTheFlyTransformation.setObjectName(_fromUtf8("checkBoxUseOnTheFlyTransformation"))
        self.verticalLayout_3.addWidget(self.checkBoxUseOnTheFlyTransformation)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maxZoomlevelSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.maxZoomlevelSpinBox.setKeyboardTracking(False)
        self.maxZoomlevelSpinBox.setMinimum(0)
        self.maxZoomlevelSpinBox.setMaximum(30)
        self.maxZoomlevelSpinBox.setProperty("value", 18)
        self.maxZoomlevelSpinBox.setObjectName(_fromUtf8("maxZoomlevelSpinBox"))
        self.gridLayout.addWidget(self.maxZoomlevelSpinBox, 1, 1, 1, 1)
        self.maxZoomlevelLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.maxZoomlevelLabel.setObjectName(_fromUtf8("maxZoomlevelLabel"))
        self.gridLayout.addWidget(self.maxZoomlevelLabel, 1, 0, 1, 1)
        self.minZoomlevelLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.minZoomlevelLabel.setObjectName(_fromUtf8("minZoomlevelLabel"))
        self.gridLayout.addWidget(self.minZoomlevelLabel, 0, 0, 1, 1)
        self.dpiLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.dpiLabel.setObjectName(_fromUtf8("dpiLabel"))
        self.gridLayout.addWidget(self.dpiLabel, 2, 0, 1, 1)
        self.minZoomlevelSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.minZoomlevelSpinBox.setKeyboardTracking(False)
        self.minZoomlevelSpinBox.setMinimum(0)
        self.minZoomlevelSpinBox.setMaximum(30)
        self.minZoomlevelSpinBox.setObjectName(_fromUtf8("minZoomlevelSpinBox"))
        self.gridLayout.addWidget(self.minZoomlevelSpinBox, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dpiSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.dpiSpinBox.setEnabled(False)
        self.dpiSpinBox.setKeyboardTracking(False)
        self.dpiSpinBox.setMinimum(72)
        self.dpiSpinBox.setMaximum(768)
        self.dpiSpinBox.setSingleStep(2)
        self.dpiSpinBox.setProperty("value", 96)
        self.dpiSpinBox.setObjectName(_fromUtf8("dpiSpinBox"))
        self.horizontalLayout.addWidget(self.dpiSpinBox)
        self.toggleDpiToolButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/toggleDpiToolButton.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleDpiToolButton.setIcon(icon5)
        self.toggleDpiToolButton.setCheckable(True)
        self.toggleDpiToolButton.setObjectName(_fromUtf8("toggleDpiToolButton"))
        self.horizontalLayout.addWidget(self.toggleDpiToolButton)
        self.resetDpiToolButton = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.resetDpiToolButton.setIcon(icon3)
        self.resetDpiToolButton.setCheckable(False)
        self.resetDpiToolButton.setObjectName(_fromUtf8("resetDpiToolButton"))
        self.horizontalLayout.addWidget(self.resetDpiToolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.OptionsTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget)
        TileMapScaleLevelsDockWidget.setWidget(self.dockWidgetContents)
        self.actionHUD = QtGui.QAction(TileMapScaleLevelsDockWidget)
        self.actionHUD.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/actionHUD.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHUD.setIcon(icon6)
        self.actionHUD.setObjectName(_fromUtf8("actionHUD"))
        self.actionTMS = QtGui.QAction(TileMapScaleLevelsDockWidget)
        self.actionTMS.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/actionTMS.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTMS.setIcon(icon7)
        self.actionTMS.setObjectName(_fromUtf8("actionTMS"))
        self.actionLayers = QtGui.QAction(TileMapScaleLevelsDockWidget)
        self.actionLayers.setIcon(icon1)
        self.actionLayers.setObjectName(_fromUtf8("actionLayers"))

        self.retranslateUi(TileMapScaleLevelsDockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.toggleDpiToolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dpiSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TileMapScaleLevelsDockWidget)

    def retranslateUi(self, TileMapScaleLevelsDockWidget):
        TileMapScaleLevelsDockWidget.setWindowTitle(_translate("TileMapScaleLevelsDockWidget", "Tile Map Scale Levels", None))
        self.toolButtonIsActive.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Enable/Disable Scale Levels", None))
        self.toolButtonIsActive.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Enable/Disable Scale Levels", None))
        self.toolButtonIsActive.setText(_translate("TileMapScaleLevelsDockWidget", "o", None))
        self.toolButtonLayers.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add Layers", None))
        self.toolButtonLayers.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Add Layers", None))
        self.toolButtonLayers.setText(_translate("TileMapScaleLevelsDockWidget", "≡", None))
        self.buttonLoadUserDataset.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add new dataset", None))
        self.buttonLoadUserDataset.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Add new dataset", None))
        self.buttonLoadUserDataset.setText(_translate("TileMapScaleLevelsDockWidget", "OSM", None))
        self.buttonLoadRefreshUserDatasets.setToolTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets", None))
        self.buttonLoadRefreshUserDatasets.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "refresh list of datasets", None))
        self.buttonLoadRefreshUserDatasets.setText(_translate("TileMapScaleLevelsDockWidget", "OSM", None))
        self.buttonInfo.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Show information", None))
        self.buttonInfo.setStatusTip(_translate("TileMapScaleLevelsDockWidget", "Show information", None))
        self.buttonInfo.setText(_translate("TileMapScaleLevelsDockWidget", "OSM", None))
        self.groupBoxZoomlevels.setTitle(_translate("TileMapScaleLevelsDockWidget", "Zoomlevel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TileMapScaleLevelsDockWidget", "Tool", None))
        self.checkBoxHUD.setText(_translate("TileMapScaleLevelsDockWidget", "Show Head-up display", None))
        self.checkBoxUseMercator.setText(_translate("TileMapScaleLevelsDockWidget", "Use World Mercator System", None))
        self.checkBoxUseOnTheFlyTransformation.setText(_translate("TileMapScaleLevelsDockWidget", "Use \'On-The-Fly\' Transformation", None))
        self.maxZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "max Zoomlevel", None))
        self.minZoomlevelLabel.setText(_translate("TileMapScaleLevelsDockWidget", "min Zoomlevel", None))
        self.dpiLabel.setText(_translate("TileMapScaleLevelsDockWidget", "DPI", None))
        self.toggleDpiToolButton.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Allow to set dpi directly", None))
        self.toggleDpiToolButton.setText(_translate("TileMapScaleLevelsDockWidget", "...", None))
        self.resetDpiToolButton.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Reset DPI", None))
        self.resetDpiToolButton.setText(_translate("TileMapScaleLevelsDockWidget", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptionsTab), _translate("TileMapScaleLevelsDockWidget", "Options", None))
        self.actionHUD.setText(_translate("TileMapScaleLevelsDockWidget", "Head-up display", None))
        self.actionHUD.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Head-up display", None))
        self.actionTMS.setText(_translate("TileMapScaleLevelsDockWidget", "TMS Widget", None))
        self.actionTMS.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Plugin widget", None))
        self.actionLayers.setText(_translate("TileMapScaleLevelsDockWidget", "Layers", None))
        self.actionLayers.setToolTip(_translate("TileMapScaleLevelsDockWidget", "Add Layer", None))

import resources_rc
